/**
 * Exercise Framework — public API.
 *
 * Re-exports the registry and types so consumers can import from
 * one location: `../../utils/exercises`.
 */

export { ExerciseRegistry } from './ExerciseRegistry';
export {
  getFeedbackIssueIdMap,
  getKnownIssueIds,
  mapFeedbackMessagesToIssueIds,
  createLandmarkRecordingFrame,
  poseMetadataForRecording,
  replayRecording,
  replayRecordingVerbose,
  slugifyExerciseName,
} from './replay';
export {
  buildLabelingGuidance,
  evaluateCase,
  createDraftLabelFromReplay,
  evaluateDataset,
  formatMetricPercent,
  getAvailableIssues,
  getExerciseLabelPolicy,
  getLabelableIssues,
  isIssueLabelableForView,
  summarizeEvaluations,
  validateCandidateConfig,
  validateDatasetCase,
  validateLabelFile,
  validateTunableSpec,
} from './dataset';
export {
  clampTunableValue,
  cloneConfig,
  createDefaultTunableSpec,
  getConfigValue,
  mergeHeuristicConfig,
  runWithConfigBindings,
  setConfigValue,
} from './heuristicConfig';
export type {
  ExerciseState,
  ExerciseFrameContext,
  ExerciseDefinition,
  ExerciseHeuristicConfig,
  ExerciseHeuristicConfigValue,
  NumericTunable,
  OptimizationResult,
  RepResult,
  ExerciseTTSConfig,
  TunableSpec,
} from './types';
export type {
  LandmarkRecording,
  LandmarkRecordingFrame,
  LandmarkRecordingFrameContext,
  LandmarkRecordingFrameStatus,
  LandmarkRecordingLandmarkSource,
  LandmarkRecordingMetadataValueState,
  LandmarkRecordingPoseLandmarkMetadata,
  LandmarkRecordingPoseMetadata,
  LandmarkRecordingPrimarySource,
  LandmarkRecordingSchemaVersion,
  LandmarkRecordingScoreSource,
  QualityCoverage,
  ReplayRepPrediction,
  ReplayResult,
  ReplayResultVerbose,
} from './replay';
export type {
  CaseEvaluation,
  AvailableIssue,
  DatasetCase,
  DatasetEvaluation,
  DatasetSplit,
  DraftLabelMetadata,
  EvaluationMetrics,
  EvaluationTotals,
  ExerciseLabelFile,
  LabelReviewStatus,
  QualityCoverageMetrics,
  RepEvaluation,
  RepMatchStatus,
  RepLabel,
  ValidationIssue,
  ExerciseLabelPolicy,
  ScoreRangePolicy,
} from './dataset';
export {
  POSE_QUALITY_LATENCY_TARGET_MS,
  PoseQualityTracker,
  RepQualityAccumulator,
  RepQualityWindowAccumulator,
  UNSCORED_REP_FEEDBACK,
  buildDisplayedPoseQuality,
  getPoseQualityMessage,
  getPoseQualityStatusLabel,
  getUnscoredRepFeedback,
  resolveExerciseQualityProfile,
  summarizeRepQuality,
  summarizeSetTrackingQuality,
} from './shared/poseQuality';
export {
  CAMERA_ANALYSIS_STATUS_PRIORITY,
  cameraLiveFeedbackReadinessStatus,
  cameraStatusFromPoseQuality,
  cameraStatusFromPoseQualityWarning,
  cameraStatusFromCompletedRepReadiness,
  cameraStatusFromPoseStateReadiness,
  cameraStatusFromViewCueGating,
  countOnlyCameraStatus,
  createCameraLiveFeedbackReadinessState,
  createRecentCompletedRepCameraStatusState,
  fullFeedbackCameraStatus,
  limitedFeedbackCameraStatus,
  recentCompletedRepCameraStatus,
  resolveCameraAnalysisStatus,
  selectCameraAnalysisStatus,
  shouldIncludeRecentCompletedRepCameraStatus,
  summarizeCameraLiveFeedbackReadinessState,
  updateCameraLiveFeedbackReadinessState,
  updateRecentCompletedRepCameraStatusState,
} from './shared/cameraAnalysisStatus';
export type {
  ExerciseQualityProfile,
  PoseQualitySnapshot,
  PoseQualityStatus,
  PoseQualityTrackerOptions,
  PoseQualityWarning,
  RepQualityWindowState,
  RepTrackingQuality,
  SetTrackingQualitySummary,
} from './shared/poseQuality';
export type {
  CameraAnalysisFeedbackMode,
  CameraLiveFeedbackReadinessState,
  CameraLiveFeedbackReadinessSnapshot,
  CameraAnalysisStatus,
  CameraAnalysisStatusCategory,
  CameraAnalysisStatusLevel,
  CameraAnalysisStatusResolution,
  CameraAnalysisStatusSource,
  RecentCompletedRepCameraStatusState,
  ResolveCameraAnalysisStatusInput,
} from './shared/cameraAnalysisStatus';
